"""P1 RepositoryPorts - persistence contracts.

Protocols only. Services depend on these; adapters satisfy them. No repository
opens its own transaction: the caller supplies one, which is what makes
"services own transaction boundaries" a structural fact rather than a convention.

Requirements: requirements.md 10.2, NFR-REL-01.
"""

from __future__ import annotations

from dataclasses import dataclass
from collections.abc import Iterator
from typing import Any, Protocol, runtime_checkable

from tto_testgen.domain.model import (
    Artefact,
    AutomatedTest,
    ChangeEvent,
    CoverageItem,
    Feature,
    Resource,
    Run,
    StageName,
    TestCase,
    TestableRequirement,
    TraceLink,
    UnitStateRecord,
)


@dataclass(frozen=True, slots=True)
class Page:
    """A bounded result set with an opaque continuation cursor.

    The hard cap is the enforcement of NFR-SCL-04, not the filter. A tool that can
    return 10,000 rows will eventually be asked to, and the constraint would then
    be violated by a caller acting reasonably.
    """

    items: list[Any]
    next_cursor: str | None = None
    total_estimate: int | None = None

    @property
    def has_more(self) -> bool:
        return self.next_cursor is not None


@runtime_checkable
class ArtefactRepository(Protocol):
    def upsert(self, artefact: Artefact) -> Artefact: ...
    def get_by_hash(self, content_hash: str) -> Artefact | None: ...
    def query(self, *, kind: str | None = None, cursor: str | None = None,
              limit: int = 200) -> Page: ...
    def known_jira_keys(self) -> frozenset[str]: ...


@runtime_checkable
class ResourceRepository(Protocol):
    def upsert(self, resource: Resource) -> Resource: ...
    def list_all(self) -> list[Resource]: ...
    def list_unclassified(self) -> list[Resource]: ...


@runtime_checkable
class FeatureRepository(Protocol):
    def upsert(self, feature: Feature) -> Feature: ...
    def get_by_slug(self, slug: str) -> Feature | None: ...
    def list_all(self) -> list[Feature]: ...


@runtime_checkable
class RequirementRepository(Protocol):
    def upsert(self, requirement: TestableRequirement) -> TestableRequirement: ...
    def get(self, requirement_id: str) -> TestableRequirement | None: ...
    def query(self, *, feature_id: int | None = None, cursor: str | None = None,
              limit: int = 200) -> Page: ...


@runtime_checkable
class CoverageRepository(Protocol):
    def upsert_many(self, items: list[CoverageItem]) -> int: ...
    def get(self, coverage_item_id: str) -> Any | None: ...
    def volume_for_feature(self, feature_id: int) -> list[Any]: ...
    def for_requirement(self, requirement_id: str) -> list[CoverageItem]: ...
    def model_version(self, feature_id: int) -> str | None: ...
    def content_hash_for(self, feature_id: int) -> str | None: ...


@runtime_checkable
class TestCaseRepository(Protocol):
    def upsert_many(self, cases: list[TestCase], feature_slug: str) -> int: ...
    def get(self, case_id: str) -> TestCase | None: ...
    def query(self, *, feature_id: int | None = None, tag: str | None = None,
              include_obsolete: bool = False, cursor: str | None = None,
              limit: int = 200) -> Page: ...
    def bucket_candidates(self, bucket_key: str) -> list[tuple[str, Any]]: ...
    def existing_identifiers(self) -> list[str]: ...
    def for_feature_slug(self, feature_slug: str) -> list[Any]: ...
    def volume_by_feature(self) -> list[Any]: ...
    def mark_obsolete(self, case_id: str, reason: str, change_event_id: int) -> None: ...
    def count_active(self) -> int: ...


@runtime_checkable
class TraceRepository(Protocol):
    def add_many(self, links: list[TraceLink]) -> int: ...
    def for_source(self, source_id: str) -> list[TraceLink]: ...
    def all_links(self) -> list[TraceLink]: ...
    def for_target(self, target_ref: str) -> list[Any]: ...
    # Cursor-backed, for the matrix. `all_links` stays for callers that filter and
    # cap in memory anyway; the matrix is the largest read in the system and the one
    # an operator runs when the corpus is at its biggest, so its memory must not be
    # a function of corpus size (U4-NFR-SCL-05).
    def stream_links(self) -> Iterator[Any]: ...


@runtime_checkable
class EmittedViewRepository(Protocol):
    """What was written, so a hand-edit can be told from a corpus change.

    Two hashes are not enough to make that distinction: the file on disk and the
    freshly rendered content differ whenever anything changed, from either side.
    The hash recorded here is the third point (BR-U4-5.2).
    """

    def get(self, path: str) -> Any | None: ...
    def upsert(self, path: str, feature_slug: str, content_hash: str,
               case_count: int, kind: str = "view") -> None: ...
    def for_feature(self, feature_slug: str) -> list[Any]: ...


@runtime_checkable
class AutomationRepository(Protocol):
    def upsert(self, test: AutomatedTest) -> AutomatedTest: ...
    def for_case(self, case_id: str) -> AutomatedTest | None: ...
    def list_at_risk(self) -> list[AutomatedTest]: ...
    def for_feature_slug(self, feature_slug: str) -> list[Any]: ...
    def list_all(self) -> list[Any]: ...
    def clear_for_feature(self, feature_slug: str) -> int: ...
    def counts(self) -> Any: ...


@runtime_checkable
class RunStateRepository(Protocol):
    def start_run(self, run: Run) -> Run: ...
    def get_state(self, unit_ref: str, stage: StageName) -> UnitStateRecord | None: ...
    def set_state(self, record: UnitStateRecord) -> UnitStateRecord: ...
    def all_states(self, unit_ref: str | None = None) -> list[UnitStateRecord]: ...
    def current_run_id(self) -> int: ...
    def last_completed_run(self) -> Any | None: ...
    def record_baseline(self, run_id: int, head_commits: dict[str, str],
                        jira_watermark: str | None) -> None: ...
    def complete_run(self, run_id: int) -> None: ...


@runtime_checkable
class ReportRepository(Protocol):
    """Read-only aggregations. Every report figure is a query result (FR-RPT-05)."""

    def coverage_by_feature(self) -> list[Any]: ...
    def coverage_by_test_type(self) -> list[Any]: ...
    def open_gaps(self) -> list[Any]: ...
    def automation(self) -> list[Any]: ...
    def deferred(self) -> list[Any]: ...
    def retired(self) -> list[Any]: ...


@runtime_checkable
class ChangeEventRepository(Protocol):
    def add(self, event: ChangeEvent) -> ChangeEvent: ...
    def latest_for(self, source: str) -> ChangeEvent | None: ...


@runtime_checkable
class UnitOfWork(Protocol):
    """The transaction boundary. Repositories are reachable only through one."""

    resources: ResourceRepository
    artefacts: ArtefactRepository
    features: FeatureRepository
    requirements: RequirementRepository
    coverage: CoverageRepository
    cases: TestCaseRepository
    traces: TraceRepository
    views: EmittedViewRepository
    automation: AutomationRepository
    run_state: RunStateRepository
    changes: ChangeEventRepository
    reports: ReportRepository

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type, exc, tb) -> bool: ...
