"""L16 ReportRenderer - reports as Markdown and CSV, deterministically.

Reports are committed and diffed, so byte-stability matters for the same reason it
does in U5: a report that reorders itself between identical runs produces a diff full
of movement and no information, and a reader learns to skip the diff - which is the
report's only mechanism for showing what changed.

**Every figure carries its derivation.** "40 cases" is not a report; "40 cases from
12 coverage items at ISTQB-standard depth, against 47 planned" can be checked. A
figure without its derivation cannot be audited, and an unauditable coverage report is
the false confidence this system exists to remove (FR-RPT-01, U8-NFR-MNT-03).
"""

from __future__ import annotations

import csv
import io
import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Sequence

from tto_testgen.domain.privacy import screen_value as screen_personal
from tto_testgen.domain.secrets import scan_value as screen_secret

_SLUG = re.compile(r"^[a-z0-9][a-z0-9-]*$")
_ABSOLUTE = re.compile(r"(?<![\w.])/(?:Users|home|var|opt|private)/[\w.\-/]+")


class SectionStatus(str, Enum):
    """Three states, not two.

    A section with no rows means the query ran and found nothing - every requirement
    uncovered, say. `NOT_AVAILABLE` means it could not run at all. Those call for
    opposite responses, and a silent omission makes them look identical.
    """

    COMPUTED = "computed"
    NOT_AVAILABLE = "not_available"


@dataclass(slots=True)
class ReportSection:
    name: str
    title: str
    status: SectionStatus = SectionStatus.COMPUTED
    columns: tuple[str, ...] = ()
    rows: list[dict[str, Any]] = field(default_factory=list)
    derivation: str = ""
    unavailable_reason: str = ""
    producing_stage: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "status": self.status.value,
            "rows": len(self.rows),
            "derivation": self.derivation,
            "unavailable_reason": self.unavailable_reason,
            "producing_stage": self.producing_stage,
        }


@dataclass(slots=True)
class Report:
    name: str
    title: str
    sections: list[ReportSection] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "report": self.name,
            "sections": [s.to_dict() for s in self.sections],
            "unavailable": [
                s.name for s in self.sections
                if s.status is SectionStatus.NOT_AVAILABLE
            ],
        }


BANNER = (
    "> Generated by TAAS from the test corpus. Every figure is a query result; none "
    "is composed by a model. Regenerate rather than edit."
)


def _cell(value: Any) -> str:
    """One line, with pipes escaped.

    `splitlines()` rather than replacing "\n": Python splits on carriage returns,
    form feeds, vertical tabs and the Unicode line separators too, and a requirement
    statement carrying any of them would otherwise break the table row it is in.
    Replacing only "\n" left exactly that hole, and a property test found it.
    """
    if value is None:
        return ""
    return " ".join(str(value).splitlines()).replace("|", "\\|")


def render_markdown(report: Report) -> str:
    """Deterministic: no timestamps, no run ids, no absolute paths, sorted rows."""
    lines: list[str] = [f"# {report.title}", "", BANNER, ""]
    for section in report.sections:
        lines += [f"## {section.title}", ""]
        if section.status is SectionStatus.NOT_AVAILABLE:
            # Named, with the stage that would supply it - so the report is an
            # instruction rather than an absence.
            stage = (
                f" Run the **{section.producing_stage}** stage."
                if section.producing_stage
                else ""
            )
            lines += [f"*Not available: {section.unavailable_reason}.*{stage}", ""]
            continue
        if section.derivation:
            lines += [f"*{section.derivation}*", ""]
        if not section.rows:
            lines += ["_No rows._", ""]
            continue
        lines.append("| " + " | ".join(section.columns) + " |")
        lines.append("|" + "|".join("---" for _ in section.columns) + "|")
        for row in section.rows:
            lines.append(
                "| " + " | ".join(_cell(row.get(c)) for c in section.columns) + " |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_csv(section: ReportSection) -> str:
    """`csv.writer`, never string joining.

    A requirement statement can contain a comma, a quote or a newline. Joining would
    shift the columns for exactly the rows whose text is most interesting, and a
    shifted traceability matrix is worse than none because it looks right.

    `lineterminator` is pinned: the default "\\r\\n" would make the bytes depend on
    nothing observable and break byte-stability across platforms.
    """
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(section.columns)
    for row in section.rows:
        writer.writerow(["" if row.get(c) is None else str(row.get(c))
                         for c in section.columns])
    return buffer.getvalue()


def scan_rendered(text: str) -> list[str]:
    """The last line: personal data and credentials, over rendered output.

    Both were refused upstream - L9 before a case was stored, L13 before TypeScript
    was written. This catches what arrived by a path neither covers: a requirement
    statement ingested before L9 existed, or a gap subject quoting a Jira comment.
    One pass over text already in memory.
    """
    findings: list[str] = []
    for number, line in enumerate(text.splitlines(), start=1):
        personal = screen_personal(f"line {number}", line)
        if personal is not None:
            findings.append(f"line {number}: {personal.pattern}")
        secret = screen_secret(f"line {number}", line)
        if secret is not None and secret.kind != "credential-field":
            findings.append(f"line {number}: {secret.kind}")
    return findings


class ReportRenderer:
    """Renders and writes. Decides nothing about what to compute."""

    def __init__(self, reports_root: Path, formats: Sequence[str] = ("markdown", "csv")) -> None:
        self._root = Path(reports_root)
        self._formats = tuple(formats)

    def path_for(self, report_name: str, suffix: str) -> Path:
        if not _SLUG.match(report_name or ""):
            raise ValueError(
                f"report name {report_name!r} is not a safe path segment "
                "(lowercase letters, digits and hyphens only)"
            )
        return self._root / f"{report_name}{suffix}"

    def emit(self, report: Report) -> list[Path]:
        written: list[Path] = []
        if "markdown" in self._formats:
            content = render_markdown(report)
            self._guard(content, report.name)
            written.append(self._write(self.path_for(report.name, ".md"), content))
        if "csv" in self._formats:
            for section in report.sections:
                if section.status is SectionStatus.NOT_AVAILABLE or not section.rows:
                    continue
                content = render_csv(section)
                self._guard(content, f"{report.name}-{section.name}")
                written.append(
                    self._write(
                        self.path_for(f"{report.name}-{section.name}", ".csv"), content
                    )
                )
        return written

    def _guard(self, content: str, where: str) -> None:
        if _ABSOLUTE.search(content):
            raise ValueError(f"{where}: an absolute path reached a report")
        findings = scan_rendered(content)
        if findings:
            raise ValueError(f"{where}: {'; '.join(findings[:3])}")

    @staticmethod
    def _write(path: Path, content: str) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path
