"""L10 ViewRenderer - the reviewable Markdown and YAML views of a feature's cases.

SQLite is the system of record; these files are derived (Q9). Two consequences run
through everything here:

  - Rendering is deterministic and I/O-free, so the same corpus produces the same
    bytes. Without that, hand-edit detection reports every file as edited on every
    run, and the operator learns to ignore the one report that protects their work
    (U4-NFR-MNT-01).
  - A file the operator edited is skipped, never overwritten and never merged. The
    corpus is authoritative, but their edit is not derivable from anything and
    destroying it teaches them never to touch a generated file - which also means
    never correcting one (BR-U4-5.2).

P-U4-04. `render_*` take domain records and return a string; `emit` is the only
part that touches a disk or a table, which is what lets the format be tested
without either.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Sequence

_SLUG = re.compile(r"^[a-z0-9][a-z0-9-]*$")

#: Stated in every view. Inside the hashed content, so removing it is itself a
#: hand-edit and is reported rather than silently accepted.
BANNER = (
    "> Generated by TAAS. The test corpus in SQLite is the system of record - "
    "editing this file does not change it. Edits are preserved, not overwritten, "
    "and this view is then reported as stale until regenerated."
)


@dataclass(slots=True)
class ViewManifest:
    """Three outcomes, not two.

    `unchanged` is separate from `written` for the same reason U2's ingestion report
    separates skipped from succeeded: a re-emission that writes nothing is exactly
    right, and indistinguishable from a broken one unless the report says so. It is
    also what makes U4-NFR-PRF-06 measurable at all.
    """

    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    hand_edited: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, list[str]]:
        return {
            "written": sorted(self.written),
            "unchanged": sorted(self.unchanged),
            "hand_edited": sorted(self.hand_edited),
        }


def digest(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _text(value: Any) -> str:
    return "" if value is None else str(value)


def _yaml_scalar(value: Any) -> str:
    """Quote conservatively rather than guess.

    Emitted by hand rather than through PyYAML's dumper because the dumper's key
    order, line wrapping and quoting style are implementation details that may
    change between versions - and U4-NFR-MNT-01 requires bytes that do not move
    when nothing moved.
    """
    if value is None:
        return '""'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    text = str(value)
    if text == "":
        return '""'
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return f'"{escaped}"'


def _rows(case: Any, key: str) -> list[Any]:
    if isinstance(case, dict):
        return list(case.get(key) or [])
    return list(getattr(case, key, []) or [])


def _attr(case: Any, key: str, default: Any = "") -> Any:
    if isinstance(case, dict):
        value = case.get(key, default)
    else:
        value = getattr(case, key, default)
    return getattr(value, "value", value)


def _sorted_cases(cases: Sequence[Any]) -> list[Any]:
    # By identifier, which is stable. Insertion order is not: two runs that produce
    # the same corpus by different routes would render different bytes.
    return sorted(cases, key=lambda c: _text(_attr(c, "id")))


def _tags(case: Any) -> list[str]:
    raw = _attr(case, "tags", []) or []
    if isinstance(raw, str):
        import json

        try:
            raw = json.loads(raw)
        except ValueError:
            raw = [raw]
    return sorted(str(t) for t in raw)


def render_markdown(feature_slug: str, cases: Sequence[Any]) -> str:
    """The review view. Behaviour and expectations, never source documentation.

    U4-NFR-SEC-03: these files are pushed to a separate Bitbucket repository. A view
    quoting three paragraphs of an internal Confluence page has moved that page into
    a repository with a different access list, which nobody involved would have
    described as the intent.
    """
    ordered = _sorted_cases(cases)
    lines: list[str] = [
        f"# Test cases - {feature_slug}",
        "",
        BANNER,
        "",
        f"**Cases**: {len(ordered)}",
        "",
    ]
    for case in ordered:
        case_id = _text(_attr(case, "id"))
        lines += [
            f"## {case_id} - {_text(_attr(case, 'title'))}",
            "",
            f"- **Type**: {_text(_attr(case, 'test_type'))}",
            f"- **Priority**: {_text(_attr(case, 'priority'))}",
            f"- **Automatability**: {_text(_attr(case, 'automatability'))}",
            f"- **Coverage item**: {_text(_attr(case, 'coverage_item_id'))}",
        ]
        tags = _tags(case)
        if tags:
            lines.append(f"- **Tags**: {', '.join(tags)}")
        preconditions = _text(_attr(case, "preconditions"))
        if preconditions:
            lines += ["", f"**Preconditions**: {preconditions}"]

        lines += ["", "| # | Action | Expected |", "|---|---|---|"]
        for step in sorted(_rows(case, "steps"), key=lambda s: _attr(s, "ordinal") or 0):
            action = _text(_attr(step, "action")).replace("|", "\\|")
            expected = _text(_attr(step, "expected")).replace("|", "\\|")
            lines.append(f"| {_attr(step, 'ordinal')} | {action} | {expected} |")

        data = _rows(case, "test_data")
        if data:
            lines += ["", "| Field | Value | Equivalence class | Boundary |", "|---|---|---|---|"]
            for datum in sorted(
                data, key=lambda d: (_attr(d, "step_ordinal") or 0, _text(_attr(d, "field_name")))
            ):
                lines.append(
                    f"| {_text(_attr(datum, 'field_name'))} "
                    f"| {_text(_attr(datum, 'value')).replace('|', chr(92) + '|')} "
                    f"| {_text(_attr(datum, 'equivalence_class'))} "
                    f"| {_text(_attr(datum, 'boundary_relation'))} |"
                )

        links = _rows(case, "trace_links")
        if links:
            keys = sorted(
                {
                    _text(_attr(l, "resolved_jira_key") or _attr(l, "target_ref"))
                    for l in links
                }
            )
            types = sorted({_text(_attr(l, "link_type")) for l in links})
            lines += ["", f"**Traces to**: {', '.join(keys)} ({', '.join(types)})"]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_yaml(feature_slug: str, cases: Sequence[Any]) -> str:
    """The machine-readable view. Explicit key order, never dictionary order."""
    ordered = _sorted_cases(cases)
    lines: list[str] = [
        f"# {BANNER.lstrip('> ')}",
        f"feature: {_yaml_scalar(feature_slug)}",
        f"case_count: {len(ordered)}",
        "cases:",
    ]
    for case in ordered:
        lines += [
            f"  - id: {_yaml_scalar(_attr(case, 'id'))}",
            f"    title: {_yaml_scalar(_attr(case, 'title'))}",
            f"    test_type: {_yaml_scalar(_attr(case, 'test_type'))}",
            f"    priority: {_yaml_scalar(_attr(case, 'priority'))}",
            f"    automatability: {_yaml_scalar(_attr(case, 'automatability'))}",
            f"    coverage_item_id: {_yaml_scalar(_attr(case, 'coverage_item_id'))}",
        ]
        tags = _tags(case)
        lines.append(f"    tags: [{', '.join(_yaml_scalar(t) for t in tags)}]")
        lines.append("    steps:")
        for step in sorted(_rows(case, "steps"), key=lambda s: _attr(s, "ordinal") or 0):
            lines += [
                f"      - ordinal: {_attr(step, 'ordinal')}",
                f"        action: {_yaml_scalar(_attr(step, 'action'))}",
                f"        expected: {_yaml_scalar(_attr(step, 'expected'))}",
            ]
        data = _rows(case, "test_data")
        lines.append("    test_data:" if data else "    test_data: []")
        for datum in sorted(
            data, key=lambda d: (_attr(d, "step_ordinal") or 0, _text(_attr(d, "field_name")))
        ):
            lines += [
                f"      - field_name: {_yaml_scalar(_attr(datum, 'field_name'))}",
                f"        value: {_yaml_scalar(_attr(datum, 'value'))}",
                f"        equivalence_class: {_yaml_scalar(_attr(datum, 'equivalence_class'))}",
                f"        boundary_relation: {_yaml_scalar(_attr(datum, 'boundary_relation'))}",
            ]
        links = _rows(case, "trace_links")
        lines.append("    trace_links:" if links else "    trace_links: []")
        for link in sorted(links, key=lambda l: _text(_attr(l, "target_ref"))):
            lines += [
                f"      - target_ref: {_yaml_scalar(_attr(link, 'target_ref'))}",
                f"        link_type: {_yaml_scalar(_attr(link, 'link_type'))}",
                f"        resolved_jira_key: {_yaml_scalar(_attr(link, 'resolved_jira_key'))}",
            ]
    return "\n".join(lines) + "\n"


class ViewRenderer:
    """Renders and emits, with the three-way comparison that protects hand-edits."""

    def __init__(self, views_root: Path) -> None:
        self._root = Path(views_root)

    def path_for(self, feature_slug: str, suffix: str) -> Path:
        """Build a path from a validated slug.

        A feature slug is agent-supplied, and an agent-supplied path segment is a
        traversal waiting to happen. Validated against a strict pattern rather than
        sanitised: rejecting `../etc` is honest, and quietly rewriting it to `etc`
        writes a file the caller did not ask for.
        """
        if not _SLUG.match(feature_slug or ""):
            raise ValueError(
                f"feature slug {feature_slug!r} is not a safe path segment "
                "(lowercase letters, digits and hyphens only)"
            )
        return self._root / f"{feature_slug}{suffix}"

    def emit(self, feature_slug: str, cases: Sequence[Any], views) -> ViewManifest:
        """Write, skip as unchanged, or skip as hand-edited - and report all three.

        `views` is the EmittedViewRepository. The recorded hash is the third point
        that separates "the operator changed this" from "the corpus changed";
        comparing the file to freshly rendered content alone would flag every
        genuine change as an edit.
        """
        manifest = ViewManifest()
        rendered = (
            (self.path_for(feature_slug, ".md"), render_markdown(feature_slug, cases)),
            (self.path_for(feature_slug, ".yaml"), render_yaml(feature_slug, cases)),
        )
        for path, content in rendered:
            key = str(path)
            fresh = digest(content)
            recorded = views.get(key)
            recorded_hash = (
                None if recorded is None else str(dict(recorded)["content_hash"])
            )

            if path.exists() and recorded_hash is not None:
                if digest(path.read_text(encoding="utf-8")) != recorded_hash:
                    # Evaluated before `unchanged`: a file the operator edited and
                    # that the corpus also changed is still a hand-edit, and
                    # overwriting it because the corpus moved would lose the edit
                    # for a reason the operator would find arbitrary.
                    manifest.hand_edited.append(key)
                    continue

            if recorded_hash == fresh and path.exists():
                manifest.unchanged.append(key)
                continue

            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            views.upsert(key, feature_slug, fresh, len(cases))
            manifest.written.append(key)
        return manifest
