"""S7 HandoverService - assemble, verify, and stop.

**S7 has no method that pushes, branches, invokes git, or writes CI configuration.**
FR-HND-04 is therefore not a rule this service follows - it is a capability it does
not have, so a future change that forgets the rule cannot violate it. Third use of
the pattern, after P2's write-free source protocols and RunStateService's absent
`next_unit()`.

Verification has two tiers. Structural checks always run and readiness depends on
them; toolchain checks run when Node is present and are reported as `skipped` when it
is not. A skipped tier never blocks - the least obvious rule in the unit, and the one
two property tests exist to pin.

Requirements: FR-HND-01 to FR-HND-06.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Callable

from tto_testgen.domain.model import StageName, UnitState, UnitStateRecord
from tto_testgen.platform.logging import Logger
from tto_testgen.platform.result import ErrorCode, Result, err, ok

PROJECT_SLUG = "<project>"

GITIGNORE = """\
# Generated by TAAS.
node_modules/
test-results/
playwright-report/
blob-report/
playwright/.cache/

# The engineer fills this in from .env.example. It holds real credentials and must
# never be committed - which is why .env.example exists as the committed template.
.env
"""

LOCKFILE_COMMAND = ("npm", "install", "--package-lock-only")

TOOLCHAIN_COMMANDS = (
    # `npm ci` installs exactly the lockfile and fails if package.json disagrees with
    # it, which is the drift FR-HND-02 exists to catch. `--ignore-scripts` is not
    # optional: npm runs lifecycle scripts from every transitive dependency by
    # default, and verification must not be the path through which a compromised
    # package executes on the operator's workstation (NFR-SEC-13).
    ("install", ("npm", "ci", "--ignore-scripts")),
    ("compile", ("npx", "tsc", "--noEmit")),
    ("enumerate", ("npx", "playwright", "test", "--list")),
)


class CheckStatus(str, Enum):
    """Three values, not a boolean plus a flag.

    `bool | None` was the compact alternative and is a trap: `None` is falsy, so the
    first `if not result:` anyone writes treats a skipped tier as a failure - undoing
    BR-U6-2.4 by a type choice rather than by a decision.
    """

    PASSED = "passed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass(slots=True)
class TierResult:
    name: str
    status: CheckStatus
    checks: list[dict[str, Any]] = field(default_factory=list)
    skipped_reason: str = ""
    duration_ms: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "tier": self.name,
            "status": self.status.value,
            "skipped_reason": self.skipped_reason,
            "duration_ms": self.duration_ms,
            "failures": [c for c in self.checks if not c.get("passed", True)],
            "checks_run": len(self.checks),
        }


@dataclass(slots=True)
class HandoverReport:
    project_root: str
    structural: TierResult
    toolchain: TierResult
    reconciliation: TierResult
    manifest_path: str = ""
    lockfile_present: bool = False
    lockfile_action: str = ""
    totals: dict[str, int] = field(default_factory=dict)
    at_risk: list[str] = field(default_factory=list)

    @property
    def is_ready(self) -> bool:
        """Readiness names all three states explicitly.

        A failed toolchain tier blocks; a skipped one does not. Written as three
        terms so the skipped case is visible in the expression rather than inferred
        from an omission.
        """
        return (
            self.structural.status is CheckStatus.PASSED
            and self.reconciliation.status is CheckStatus.PASSED
            and self.toolchain.status is not CheckStatus.FAILED  # SKIPPED does not block
        )

    def blocking(self) -> list[dict[str, Any]]:
        out: list[dict[str, Any]] = []
        for tier in (self.structural, self.reconciliation, self.toolchain):
            if tier.status is CheckStatus.FAILED:
                out += [c for c in tier.checks if not c.get("passed", True)]
        return out

    def to_dict(self) -> dict[str, Any]:
        return {
            "project_root": self.project_root,
            "is_ready": self.is_ready,
            "structural": self.structural.to_dict(),
            "toolchain": self.toolchain.to_dict(),
            "reconciliation": self.reconciliation.to_dict(),
            "manifest_path": self.manifest_path,
            "lockfile_present": self.lockfile_present,
            "lockfile_action": self.lockfile_action,
            "totals": self.totals,
            "at_risk": sorted(self.at_risk),
            "blocking": self.blocking(),
            "derivation": (
                "ready when structural checks and reconciliation pass. A skipped "
                "toolchain tier does not block; a failed one does. The system "
                "reports readiness; the handover gate is the operator's."
            ),
        }


class HandoverService:
    """Assembles, verifies, reports. Writes nothing to the corpus but the outcome."""

    def __init__(
        self,
        uow_factory: Callable[[], Any],
        run_state: Any,
        verifier: Any,
        runner: Any,
        logger: Logger,
        *,
        project_root: Path,
        command_timeout_s: int = 300,
        skip_toolchain: bool = False,
    ) -> None:
        self._uow_factory = uow_factory
        self._run_state = run_state
        self._verifier = verifier
        self._runner = runner
        self._logger = logger
        self._root = Path(project_root)
        self._timeout_s = command_timeout_s
        self._skip_toolchain = skip_toolchain

    # --- the handover -----------------------------------------------------------

    def assemble(self, *, run_id: int | None = None) -> Result[HandoverReport]:
        gate = self._run_state.is_gate_open(PROJECT_SLUG, StageName.HANDOVER)
        if not gate.is_open:
            return err(
                ErrorCode.REJECTED_GATE_CLOSED, gate.detail, remediation=gate.remediation
            )
        if not self._root.exists():
            return err(
                ErrorCode.FAILED_INTERNAL,
                f"No generated project at {self._root}",
                remediation="Run automation_emit for at least one feature first.",
            )

        self._write_gitignore()
        lockfile_present, lockfile_action = self._ensure_lockfile()

        with self._uow_factory() as uow:
            tests = [dict(r) for r in uow.automation.list_all()]
            # A case row carries its tags but not its links, so the Jira key is read
            # per test rather than joined - there is one test per case, so this is
            # bounded by the suite size rather than by the corpus.
            cases = {}
            for test in tests:
                case_id = str(test["case_id"])
                row = uow.cases.get(case_id)
                if row is None:
                    continue
                record = dict(row)
                record["trace_links"] = [
                    dict(l) for l in uow.traces.for_source(case_id)
                ]
                cases[case_id] = record
            totals = self._totals(uow)

        manifest, manifest_path = self._write_manifest(tests, cases, totals)
        structural = self._verify_structure()
        reconciliation = self._reconcile(tests, manifest)
        toolchain = self._verify_toolchain()

        report = HandoverReport(
            project_root=str(self._root),
            structural=structural,
            toolchain=toolchain,
            reconciliation=reconciliation,
            manifest_path=str(manifest_path),
            lockfile_present=lockfile_present,
            lockfile_action=lockfile_action,
            totals=totals,
            at_risk=[str(t["id"]) for t in tests if t.get("is_at_risk")],
        )
        self._record(report, run_id)
        self._logger.info(
            "handover assembled", ready=report.is_ready,
            structural=structural.status.value, toolchain=toolchain.status.value,
        )
        return ok(report)

    def verify(self) -> Result[HandoverReport]:
        """Re-run every check without rewriting the manifest.

        Nothing is cached between runs. The operator re-runs after every fix, and the
        file most likely to have changed is the one they just fixed - a resumed run
        that skipped a previously-passing check would report a stale pass for exactly
        that file.
        """
        if not self._root.exists():
            return err(ErrorCode.FAILED_INTERNAL, f"No project at {self._root}")

        manifest = self._read_manifest()
        with self._uow_factory() as uow:
            tests = [dict(r) for r in uow.automation.list_all()]
            totals = self._totals(uow)

        report = HandoverReport(
            project_root=str(self._root),
            structural=self._verify_structure(),
            toolchain=self._verify_toolchain(),
            reconciliation=self._reconcile(tests, manifest),
            manifest_path=str(self._root / "handover-manifest.json"),
            lockfile_present=(self._root / "package-lock.json").exists(),
            totals=totals,
            at_risk=[str(t["id"]) for t in tests if t.get("is_at_risk")],
        )
        return ok(report)

    # --- assembly ------------------------------------------------------------------

    def _write_gitignore(self) -> None:
        path = self._root / ".gitignore"
        if not path.exists():
            _atomic_write(path, GITIGNORE)

    def _ensure_lockfile(self) -> tuple[bool, str]:
        path = self._root / "package-lock.json"
        if path.exists():
            return True, "already present"
        if self._skip_toolchain or not self._runner.is_available("npm"):
            # A missing file with the exact command beside it is a two-second fix.
            # A missing file with no explanation is a puzzle - and the operator's
            # first guess, `npm install`, also creates a 500 MB node_modules.
            return False, (
                "not generated: npm not available. Run "
                f"`{' '.join(LOCKFILE_COMMAND)}` in the project before pushing."
            )
        result = self._runner.run(
            list(LOCKFILE_COMMAND), cwd=self._root, timeout_s=self._timeout_s
        )
        if result.succeeded and path.exists():
            return True, "generated with npm install --package-lock-only"
        return False, f"generation failed: {result.summary()}"

    # --- verification -------------------------------------------------------------------

    def _verify_structure(self) -> TierResult:
        checks = [
            {"name": c.name, "passed": c.passed, "location": c.location,
             "detail": c.detail}
            for c in self._verifier.verify(self._root)
        ]
        failed = any(not c["passed"] for c in checks)
        return TierResult(
            name="structural",
            status=CheckStatus.FAILED if failed else CheckStatus.PASSED,
            checks=checks,
        )

    def _verify_toolchain(self) -> TierResult:
        if self._skip_toolchain:
            return TierResult("toolchain", CheckStatus.SKIPPED,
                              skipped_reason="disabled by configuration")
        for executable in ("npm", "npx"):
            if not self._runner.is_available(executable):
                return TierResult(
                    "toolchain", CheckStatus.SKIPPED,
                    skipped_reason=f"{executable} not found on PATH",
                )

        checks: list[dict[str, Any]] = []
        elapsed = 0
        for name, argv in TOOLCHAIN_COMMANDS:
            result = self._runner.run(list(argv), cwd=self._root, timeout_s=self._timeout_s)
            elapsed += result.duration_ms
            checks.append({
                "name": name,
                "passed": result.succeeded,
                "location": " ".join(argv),
                # A tool that was absent is skipped; one that ran and did not finish
                # is failed. Folding a timeout into skipped would tell the operator
                # their machine lacks Node when it does not.
                "detail": "" if result.succeeded else _failure_detail(result),
            })
            if not result.succeeded:
                break  # tsc needs node_modules; running on is noise, not information
        failed = any(not c["passed"] for c in checks)
        return TierResult(
            name="toolchain",
            status=CheckStatus.FAILED if failed else CheckStatus.PASSED,
            checks=checks,
            duration_ms=elapsed,
        )

    def _reconcile(self, tests: list[dict], manifest: dict) -> TierResult:
        """Three-way: the corpus, the disk, and the manifest.

        Two-way against the database alone misses a spec deleted by hand; against
        disk alone misses a test the database believes exists. Both are reachable,
        because the design explicitly permits editing the project.
        """
        import re

        in_db = {str(t["case_id"]) for t in tests}
        on_disk: set[str] = set()
        pattern = re.compile(r"TC-[A-Z0-9-]+-\d{5}")
        for spec in sorted((self._root / "tests").glob("*.spec.ts")):
            try:
                on_disk |= set(pattern.findall(spec.read_text(encoding="utf-8")))
            except OSError:
                continue
        in_manifest = {str(e["case_id"]) for e in manifest.get("entries", [])}

        comparisons = (
            ("in the corpus but not on disk", sorted(in_db - on_disk)),
            ("on disk but not in the corpus", sorted(on_disk - in_db)),
            ("on disk but not in the manifest", sorted(on_disk - in_manifest)),
            ("in the manifest but not on disk", sorted(in_manifest - on_disk)),
        )
        checks = [
            {"name": f"reconciliation: nothing {label}", "passed": not missing,
             "location": "handover-manifest.json",
             "detail": "" if not missing else f"{len(missing)}: {', '.join(missing[:5])}"}
            for label, missing in comparisons
        ]
        failed = any(not c["passed"] for c in checks)
        return TierResult(
            name="reconciliation",
            status=CheckStatus.FAILED if failed else CheckStatus.PASSED,
            checks=checks,
        )

    # --- the manifest ----------------------------------------------------------------------

    def _write_manifest(
        self, tests: list[dict], cases: dict[str, dict], totals: dict[str, int]
    ) -> tuple[dict, Path]:
        entries = []
        for test in sorted(tests, key=lambda t: str(t["id"])):
            case = cases.get(str(test["case_id"]), {})
            entries.append({
                "test_id": str(test["id"]),
                "case_id": str(test["case_id"]),
                "test_name": str(test["test_name"]),
                # Relative: the manifest is committed and read on other machines, and
                # an absolute path would name the generating workstation.
                "spec_path": _relative(str(test["spec_path"]), self._root),
                "jira_key": _jira_key(case),
                "tags": _tags(case),
                "is_at_risk": bool(test.get("is_at_risk")),
                "at_risk_reason": str(test.get("at_risk_reason") or ""),
            })
        manifest = {
            "entries": entries,
            "totals": totals,
            "at_risk_count": sum(1 for e in entries if e["is_at_risk"]),
        }
        path = self._root / "handover-manifest.json"
        _atomic_write(path, json.dumps(manifest, indent=2, sort_keys=True) + "\n")
        _atomic_write(self._root / "handover-manifest.md", _render_manifest(manifest))
        return manifest, path

    def _read_manifest(self) -> dict:
        path = self._root / "handover-manifest.json"
        if not path.exists():
            return {"entries": []}
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except ValueError:
            return {"entries": []}

    def _totals(self, uow: Any) -> dict[str, int]:
        counts = dict(uow.automation.counts())
        rows = [dict(r) for r in uow.cases.volume_by_feature()]
        return {
            "automated": int(counts.get("total") or 0),
            "at_risk": int(counts.get("at_risk") or 0),
            "manual_only": sum(int(r.get("manual_only") or 0) for r in rows),
            "needs_review": sum(int(r.get("needs_review") or 0) for r in rows),
            "corpus_total": sum(int(r.get("cases") or 0) for r in rows),
        }

    def _record(self, report: HandoverReport, run_id: int | None) -> None:
        """`unit_state.metrics` already holds an outcome. A handover is an event, and
        storing the manifest would create a second copy of the corpus that goes stale
        the moment a case changes."""
        with self._uow_factory() as uow:
            uow.run_state.set_state(
                UnitStateRecord(
                    unit_ref=PROJECT_SLUG,
                    stage=StageName.HANDOVER,
                    state=UnitState.COMPLETED if report.is_ready else UnitState.NEEDS_REVIEW,
                    metrics={
                        "is_ready": report.is_ready,
                        "structural": report.structural.status.value,
                        "toolchain": report.toolchain.status.value,
                        **report.totals,
                    },
                )
            )


def _failure_detail(result: Any) -> str:
    if getattr(result, "timed_out", False):
        return f"timed out after {result.duration_ms} ms"
    tail = (result.stderr or result.stdout or "").strip()
    return f"exit {result.exit_code}: {tail[-500:]}" if tail else f"exit {result.exit_code}"


def _relative(path: str, root: Path) -> str:
    try:
        return str(Path(path).relative_to(root))
    except ValueError:
        return Path(path).name


def _jira_key(case: dict) -> str:
    links = case.get("trace_links") or []
    keys = sorted(str(l.get("resolved_jira_key") or l.get("target_ref")) for l in links)
    return keys[0] if keys else ""


def _tags(case: dict) -> list[str]:
    raw = case.get("tags") or []
    if isinstance(raw, str):
        try:
            raw = json.loads(raw)
        except ValueError:
            raw = [raw]
    return sorted(str(t) for t in raw)


def _render_manifest(manifest: dict) -> str:
    totals = manifest["totals"]
    lines = [
        "# Handover Manifest",
        "",
        "Generated by TAAS. Rewritten on every handover — do not edit.",
        "",
        "| Measure | Count |",
        "|---|---|",
        f"| Automated | {totals.get('automated', 0)} |",
        f"| Manual only | {totals.get('manual_only', 0)} |",
        f"| Needs review | {totals.get('needs_review', 0)} |",
        f"| Corpus total | {totals.get('corpus_total', 0)} |",
        f"| At risk | {manifest.get('at_risk_count', 0)} |",
        "",
        "| Test | Case | Jira | Tags | Spec | At risk |",
        "|---|---|---|---|---|---|",
    ]
    for entry in manifest["entries"]:
        lines.append(
            f"| {entry['test_id']} | {entry['case_id']} | {entry['jira_key']} "
            f"| {', '.join(entry['tags'])} | {entry['spec_path']} "
            f"| {'yes' if entry['is_at_risk'] else ''} |"
        )
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, content: str) -> None:
    """Reconciliation reads the manifest, so a truncated file from a crashed run
    would be read as authoritative by the next run - producing a failure with no
    cause the engineer can find. Same directory keeps the rename on one filesystem."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(path.name + ".tmp")
    temp.write_text(content, encoding="utf-8")
    os.replace(temp, path)
